FROM golang:1.18.1-buster

RUN go version
ENV GOPATH=/

COPY ./ ./


RUN apt-get update 
RUN apt-get -y install postgresql-client 

RUN go mod download 
RUN go build -o store-strimenko ./cmd/main.go 



CMD ["./store-strimenko"]